/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfertaAcademicaIndexRouteImport } from './routes/OfertaAcademica/index'
import { Route as ManageUsersIndexRouteImport } from './routes/ManageUsers/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaAcademicaIndexRoute = OfertaAcademicaIndexRouteImport.update({
  id: '/OfertaAcademica/',
  path: '/OfertaAcademica/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageUsersIndexRoute = ManageUsersIndexRouteImport.update({
  id: '/ManageUsers/',
  path: '/ManageUsers/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ManageUsers/': typeof ManageUsersIndexRoute
  '/OfertaAcademica/': typeof OfertaAcademicaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ManageUsers': typeof ManageUsersIndexRoute
  '/OfertaAcademica': typeof OfertaAcademicaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ManageUsers/': typeof ManageUsersIndexRoute
  '/OfertaAcademica/': typeof OfertaAcademicaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ManageUsers/' | '/OfertaAcademica/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ManageUsers' | '/OfertaAcademica'
  id: '__root__' | '/' | '/ManageUsers/' | '/OfertaAcademica/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageUsersIndexRoute: typeof ManageUsersIndexRoute
  OfertaAcademicaIndexRoute: typeof OfertaAcademicaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/OfertaAcademica/': {
      id: '/OfertaAcademica/'
      path: '/OfertaAcademica'
      fullPath: '/OfertaAcademica/'
      preLoaderRoute: typeof OfertaAcademicaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ManageUsers/': {
      id: '/ManageUsers/'
      path: '/ManageUsers'
      fullPath: '/ManageUsers/'
      preLoaderRoute: typeof ManageUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageUsersIndexRoute: ManageUsersIndexRoute,
  OfertaAcademicaIndexRoute: OfertaAcademicaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
