/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeguimientoRouteImport } from './routes/Seguimiento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageUsersIndexRouteImport } from './routes/ManageUsers/index'

const SeguimientoRoute = SeguimientoRouteImport.update({
  id: '/Seguimiento',
  path: '/Seguimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageUsersIndexRoute = ManageUsersIndexRouteImport.update({
  id: '/ManageUsers/',
  path: '/ManageUsers/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Seguimiento': typeof SeguimientoRoute
  '/ManageUsers/': typeof ManageUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Seguimiento': typeof SeguimientoRoute
  '/ManageUsers': typeof ManageUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Seguimiento': typeof SeguimientoRoute
  '/ManageUsers/': typeof ManageUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Seguimiento' | '/ManageUsers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Seguimiento' | '/ManageUsers'
  id: '__root__' | '/' | '/Seguimiento' | '/ManageUsers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeguimientoRoute: typeof SeguimientoRoute
  ManageUsersIndexRoute: typeof ManageUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Seguimiento': {
      id: '/Seguimiento'
      path: '/Seguimiento'
      fullPath: '/Seguimiento'
      preLoaderRoute: typeof SeguimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ManageUsers/': {
      id: '/ManageUsers/'
      path: '/ManageUsers'
      fullPath: '/ManageUsers/'
      preLoaderRoute: typeof ManageUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeguimientoRoute: SeguimientoRoute,
  ManageUsersIndexRoute: ManageUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
