/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoporteIndexRouteImport } from './routes/Soporte/index'
import { Route as SeleccionAsignaturasIndexRouteImport } from './routes/SeleccionAsignaturas/index'
import { Route as ManageUsersIndexRouteImport } from './routes/ManageUsers/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteIndexRoute = SoporteIndexRouteImport.update({
  id: '/Soporte/',
  path: '/Soporte/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeleccionAsignaturasIndexRoute =
  SeleccionAsignaturasIndexRouteImport.update({
    id: '/SeleccionAsignaturas/',
    path: '/SeleccionAsignaturas/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManageUsersIndexRoute = ManageUsersIndexRouteImport.update({
  id: '/ManageUsers/',
  path: '/ManageUsers/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ManageUsers/': typeof ManageUsersIndexRoute
  '/SeleccionAsignaturas/': typeof SeleccionAsignaturasIndexRoute
  '/Soporte/': typeof SoporteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ManageUsers': typeof ManageUsersIndexRoute
  '/SeleccionAsignaturas': typeof SeleccionAsignaturasIndexRoute
  '/Soporte': typeof SoporteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ManageUsers/': typeof ManageUsersIndexRoute
  '/SeleccionAsignaturas/': typeof SeleccionAsignaturasIndexRoute
  '/Soporte/': typeof SoporteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ManageUsers/' | '/SeleccionAsignaturas/' | '/Soporte/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ManageUsers' | '/SeleccionAsignaturas' | '/Soporte'
  id:
    | '__root__'
    | '/'
    | '/ManageUsers/'
    | '/SeleccionAsignaturas/'
    | '/Soporte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageUsersIndexRoute: typeof ManageUsersIndexRoute
  SeleccionAsignaturasIndexRoute: typeof SeleccionAsignaturasIndexRoute
  SoporteIndexRoute: typeof SoporteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Soporte/': {
      id: '/Soporte/'
      path: '/Soporte'
      fullPath: '/Soporte/'
      preLoaderRoute: typeof SoporteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SeleccionAsignaturas/': {
      id: '/SeleccionAsignaturas/'
      path: '/SeleccionAsignaturas'
      fullPath: '/SeleccionAsignaturas/'
      preLoaderRoute: typeof SeleccionAsignaturasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ManageUsers/': {
      id: '/ManageUsers/'
      path: '/ManageUsers'
      fullPath: '/ManageUsers/'
      preLoaderRoute: typeof ManageUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageUsersIndexRoute: ManageUsersIndexRoute,
  SeleccionAsignaturasIndexRoute: SeleccionAsignaturasIndexRoute,
  SoporteIndexRoute: SoporteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
